---
- name: Run apt-cacher-ng container
  hosts: all
  connection: local
  gather_facts: no
  serial: 1
  roles:
    - role: winggundamth.apt_cacher_ng_container
  vars_files:
    - "{{ docker_machine_vars_file }}"
    - "{{ apt_cacher_ng_container_vars_file }}"
