---
- name: Run elasticsearch container
  hosts: all
  connection: local
  gather_facts: no
  serial: 1
  roles:
    - role: winggundamth.elasticsearch_container
  vars_files:
    - "{{ docker_machine_vars_file }}"
    - "{{ elasticsearch_container_vars_file }}"
