---
- name: Launch OpenStack instance(s)
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - winggundamth.openstack_launch_instances

- name: Install python2
  hosts: launched_openstack_instances
  gather_facts: no
  become: true
  tasks:
    - name: Install Python 2
      raw: "(test -f /etc/apt/apt.conf.d/11proxy ||
        echo 'Acquire::http::Proxy \"{{ host_preparation_apt_cacher_ng }}\";' >
          /etc/apt/apt.conf.d/11proxy) &&
        python --version || apt-get update && apt-get install -y python"

- name: Configure instance(s)
  hosts: launched_openstack_instances
  gather_facts: yes
  become: true
  roles:
    - { role: winggundamth.host_preparation, when: ansible_uptime_seconds < 300 }
    - { role: winggundamth.install_docker, when: ansible_uptime_seconds < 300 }
    - { role: winggundamth.newrelic, when: ansible_uptime_seconds < 300 and newrelic_license_key is defined }

- name: Configure Docker Machine
  hosts: launched_openstack_instances
  connection: local
  gather_facts: yes
  become: false
  roles:
    - role: winggundamth.docker_machine
      docker_machine_create: true
      docker_machine_manage_config: true

- name: Deploy service
  hosts: launched_openstack_instances
  connection: local
  gather_facts: yes
  serial: 1
  roles:
    - { role: winggundamth.automated_docker, when: automated_docker_name is defined }

- name: Deploy Keepalived
  hosts: launched_openstack_instances
  gather_facts: no
  become: true
  roles:
    - { role: winggundamth.keepalived, when: os_instance.count > 1 and automated_docker_name == 'haproxy' }
