---
- name: Run Nginx container
  hosts: all
  connection: local
  gather_facts: no
  serial: 1
  roles:
    - role: winggundamth.nginx_container
  vars_files:
    - "{{ docker_machine_vars_file }}"
    - "{{ nginx_container_vars_file }}"
